name: Run Tests
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}
on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  test:
    runs-on: [ self-hosted, non-api ]
    strategy:
      max-parallel: 4
      matrix:
        go-version: ["1.23"]

    name: Run Tests
    steps:
      - name: checkout
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0

      - name: setup golang
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version: '${{ matrix.go-version }}'

      - run: sh ./run_tests.sh
        env:
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
          GOPRIVATE: github.com/razorpay/*