name: Run Tests
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}
on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  test:
    runs-on: [ self-hosted, non-api ]
    strategy:
      max-parallel: 4
      matrix:
        go-version: ["1.23"]

    name: Run Tests
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup golang
        uses: actions/setup-go@v5
        with:
          go-version: '${{ matrix.go-version }}'

      - run: sh ./run_tests.sh
        env:
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
          GOPRIVATE: github.com/razorpay/*